### ISSUE TITLE
Bug? - Unable to attack opposite team players with weapons

### ISSUE THREAD

**Issue by Owizardo** [kangarko/Puncher#12]
Hi there,

Not sure if this was intentional but after spending alot of time getting my classes, custom weapons and arena maps in order. Just noticed that you cant attack another player with any sort of weapons except for the those in the /p items. Is where a way to enable this?  I don't even mind if there's friendly fire 

Just to provide an example, I have arenas setup in a way where you can either knock an opponent ouf of the map, kill your opponents or destroy the map until only one remains standing. Any easy way to accomplish this?

**Comment by kangarko** [comment]
Hello,

by the game convention there is no PvP in a sense of killing players with weapons, but since Puncher shares some background code of CoreArena it has a leftover of a code that makes that possible. Here's how: Add "PvP: 1" key and value to "Phase" section in your arena yml file.

Please note that enabling unsupported features may lead to unexpected behaviour since Puncher doesn't support this nativelly. Please report all such.
